Repository jenkinsci/build-user-vars-plugin, pull requests merged in 2024-10, with the labels that each got.

#146 Update plugin parent POM to latest
  pom.xml
Labels: dependencies, java

#147 add coverage badge
  README.md
Labels: documentation

#149 Require Jenkins 2.479.1 LTS or newer
  pom.xml
Labels: skip-changelog
